### ISSUE TITLE
Train with CUDA meet Error: raise ValueError("can't optimize a non-leaf Tensor")

### ISSUE THREAD

**Issue by Li-Jinquan** [Linardos/SalEMA#7] opened 2020-07-19 13:26 UTC
Hi, When I train this model use "python train.py -dataset=DHF1K -pt_model=False -new_model=SalEMA -ema_loc=30 -start=1 -end=10 -src=F:/2/DHF1K -use_gpu='gpu' -epochs=7", It repoert error like this:
`Commencing training on dataset DHF1K
Size of train set is 1
Initial alpha set to: tensor([0.2500], device='cuda:0', grad_fn=<CopyBackwards>)
Model initialized, EMA located at Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
Initialized SalEMA with residual set to False and dropout set to True
Traceback (most recent call last):
  File "train.py", line 518, in <module>
    main(args)
  File "train.py", line 147, in main
    optimizer = torch.optim.Adam([{'params':model.salgan.parameters() , 'lr': args.lr, 'weight_decay':weight_decay},{'params':model.alpha, 'lr': 0.1}])
  File "D:\App\Anaconda\lib\site-packages\torch\optim\adam.py", line 42, in __init__
    super(Adam, self).__init__(params, defaults)
  File "D:\App\Anaconda\lib\site-packages\torch\optim\optimizer.py", line 50, in __init__
    self.add_param_group(param_group)
  File "D:\App\Anaconda\lib\site-packages\torch\optim\optimizer.py", line 200, in add_param_group
    raise ValueError("can't optimize a non-leaf Tensor")
ValueError: can't optimize a non-leaf Tensor
`
Can you help me? The environment is the same as the requirement.

**Comment by Linardos** [comment] 2020-08-07 12:44
Hi Li. Sorry for the delay in getting back to your question. 

Hmm, I don't recall ever encountering this error before. I wonder if optimizing the alpha parameter is what's causing this in your case. 
I changed some things in [train.py](https://github.com/Linardos/SalEMA/blob/master/src/train.py) now so that you can set a fixed alpha value (Lines 147-153 and Line 125)
Could you set -alpha=0.08 and tell me if you're still getting this error? Unfortunately I can't reproduce it myself at the current time.

**Comment by Li-Jinquan** [comment] 2020-08-08 00:51
Hi Linardos, 
Thanks for replying me,  I find out it occurs because in "SalEMA.py" line 100 to line 117. The data was not put in cuda successfully. I add some ".cuda()" on it and it works. Thanks a lot!!!!!!

**Comment by Linardos** [comment] 2020-08-11 12:47
Glad you resolved it. It seems strange though, the model is moved to cuda in the [train.py](https://github.com/Linardos/SalEMA/blob/master/src/train.py#L188) line 188. Did you use parallel or standard cuda?

I'll close this issue but do let me know where you had to add cuda in the lines you mentioned for it to work. It might help the next fellow that runs into this problem.

**Closed by Linardos** 2020-08-11 12:47 UTC

**Comment by Li-Jinquan** [comment] 2020-08-12 10:07
Here are the codes, on my computer the "salgan" model was not put in cuda for some unknown reasons, here are my code:
`  def forward(self, input_, prev_state=None):
        self.salgan = self.salgan.cuda()
        input_ = input_.cuda()

        x = self.salgan[:self.ema_loc](input_)
        residual = x
        batch_size = x.data.size()[0]
        spatial_size = x.data.size()[2:]

        if self.dropout == True:
            x = dropout2d(x)
        # salgan[self.ema_loc] will act as the temporal state
        if prev_state is None:
            current_state = self.salgan.cuda()[self.ema_loc](x.cuda()) #Initially don't apply alpha as there is no prev state we will consistently have bad saliency maps at the start if we were to do so.
        else:
            current_state = torch.sigmoid(self.alpha).cuda()*self.salgan[self.ema_loc](x)+(1-torch.sigmoid(self.alpha).cuda())*prev_state`
